Create index.d.ts
sindresorhus/is-port-reachable pull request #8
Opened 2021-09-18 14:09 UTC by mikicho

Add typescript definition file to solve ts(7016)

2021-09-18 14:13 UTC, sindresorhus commented
Thanks for creating a TypeScript definition. 🙌 Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

Some examples:
- https://github.com/sindresorhus/semver-regex/commit/039944bb5b3876913171b895488874b5c200e458
- https://github.com/sindresorhus/global-dirs/commit/0aae4d64887f77af94c4fb7ca12aa9f93c0a8291
- https://github.com/sindresorhus/md5-hex/commit/bbbfeff840f26973fbffc16d4863ae6d120079f3

2021-09-18 14:40 UTC, mikicho commented
@sindresorhus done.
Please let me know if I missed something.

2021-09-18 18:11 UTC, sindresorhus commented on index.d.ts
> +}
Use the same example as the readme.

2021-09-18 18:11 UTC, sindresorhus commented on index.d.ts
> +declare function isPortReachable(port: number, opts?: {timeout?: number, host?: string}): Promise<boolean>;
Options should follow the style here: https://github.com/sindresorhus/typescript-definition-style-guide#documentation

2021-09-18 19:36 UTC, mikicho commented
@sindresorhus  done

2021-09-19 08:10 UTC, sindresorhus requested changes

2021-09-19 08:10 UTC, sindresorhus commented on index.d.ts
> +  timeout?: number;
Use tab-indentation.

2021-09-19 08:10 UTC, sindresorhus commented on index.d.ts
> +  @default localhost
```suggestion
  @default 'localhost'
```

2021-09-19 08:10 UTC, sindresorhus commented on package.json
> +    "index.d.ts"
Incorrect indentation

2021-09-19 08:11 UTC, sindresorhus commented on index.d.ts
> +interface IsPortReachableOptions {
```suggestion
interface Options {
```

2021-09-19 08:11 UTC, sindresorhus commented
The pull request needs a proper title.

2021-09-19 08:17 UTC, mikicho commented
@sindresorhus done

2021-09-19 08:52 UTC, merged